# Default values for helmTasl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2


appdeployment:
  name: python-app-deployment
  label: python-app
  containers:
    name: python-application
    image: moutazmuhammad/pythonapp


databasedeployment:
  name: redis-deployment
  label: redis-app
  containers:
    name: redis-database
    image: redis

frontservice:
  name: frontend-svc
  selector: python-app
  type: NodePort
  nodePort: 32100

backservice:
  name: backend-svc
  selector: redis-app
  type: ClusterIP


ENVIRONMENT: DEV
HOST: localhost
PORT: 8000
REDIS_PORT: 6379
REDIS_DB: 0