apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: {{.Values.frontservice.selector}}
  type: {{.Values.frontservice.type}}
  ports:
    - port: {{.Values.PORT}}
      targetPort: {{.Values.PORT}}
      nodePort: {{.Values.frontservice.nodePort}}
      protocol: TCP
      