apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_metadata.backend_name }}
spec:
  type: {{ .Values.svc_type.backend_type }}
  ports:
  - port: {{ .Values.svc_port.backend.port }}
    targetPort: {{ .Values.svc_port.backend.targetPort }}
  selector:
    {{- range $k, $v := .Values.svc_selector.backend }}
    {{ $k }}: {{ $v }}
    {{- end }}