apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_metadata.frontend_name }}
spec:
  type: {{ .Values.svc_type.frontend_type }}
  ports:
  - port: {{ .Values.svc_port.frontend.port }}
    targetPort: {{ .Values.svc_port.frontend.targetPort }}
    nodePort: {{ .Values.svc_port.frontend.nodePort }}
  selector:
    {{- range $k, $v := .Values.svc_selector.frontend }}
    {{ $k }}: {{ $v }}
    {{- end }}